car/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cars/', views.cars_index, name='index'),
    path('cars/<int:car_id>/', views.cars_detail, name='detail'),
    path('cars/create/', views.CarCreate.as_view(), name='cars_create'),
    path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name='car_update'),
    path('cats/<int:pk>/delete/', views.CarDelete.as_view(), name='car_delete'),
    path('cars/<int:car_id>/add_service/', views.add_maintain, name='add_maintain'),
    path('fluids/', views.FluidList.as_view(), name='fluids_index'),
    path('fluids/<int:pk>/', views.FluidDetail.as_view(), name='fluids_detail'),
    path('fluids/create/', views.FluidCreate.as_view(), name='fluids_create'),
    path('fluids/<int:pk>/update/', views.FluidUpdate.as_view(), name='fluids_update'),
    path('fluids/<int:pk>/delete/', views.FluidDelete.as_view(), name='fluids_delete'),
    path('cars/<int:car_id>/assoc_fluid/<int:fluid_id>/', views.assoc_fluid, name='assoc_fluid'),
    path('accounts/signup', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

SERVICE = (
    ('O', 'Oil Change'),
    ('C', 'Coolant Flush'),
    ('B', 'Brake Pads'),
    ('F', 'Fuel Filter')
)

class Fluid(models.Model):
    name = models.CharField(max_length=50)
    weight = models.CharField(max_length=30)

    def get_absolute_url(self):
        return reverse('fluids_detail', kwargs={'pk': self.id})


class Car(models.Model):
    make = models.CharField(max_length=30)
    year = models.IntegerField()
    model = models.CharField(max_length=30)
    trim = models.CharField(max_length=30)
    mileage = models.IntegerField()
    # add many to many relationship
    fluids = models.ManyToManyField(Fluid)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.model
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'car_id': self.id})

class Maintain(models.Model):
    date = models.DateField('Service Date')
    service = models.CharField(
        max_length=1,
        choices=SERVICE,
        default=SERVICE[0][0]
        )

    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_service_display()} on {self.date}"
    
    # sort by most recent date of service
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Maintain

class MaintainForm(ModelForm):
    class Meta:
        model = Maintain
        fields = ['date', 'service']

main_app/views.py
from pyexpat import model
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from .models import Car, Fluid
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import MaintainForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

@login_required
def cars_index(request):
    cars = Car.objects.filter(user=request.user)
    return render(request, 'cars/index.html', {'cars': cars})


@login_required
def cars_detail(request, car_id):
    car = Car.objects.get(id=car_id)
    fluids_car_doesnt_have = Fluid.objects.exclude(
        id__in=car.fluids.all().values_list('id'))
    # instaniate maintainform to be rendered in template
    maintain_form = MaintainForm()
    return render(request, 'cars/detail.html', {
        # includes car and feeding form in the context
        'car': car,
        'maintain_form': maintain_form,
        'fluids': fluids_car_doesnt_have
    })


@login_required
def add_maintain(request, car_id):
    # create model form using data in request.post
    form = MaintainForm(request.POST)
    # validate the form
    if form.is_valid():
        # dont save the form to the db until it has the car_id assigned
        new_maintain = form.save(commit=False)
        new_maintain.car_id = car_id
        new_maintain.save()
        # use redirect instead of render if data has been changed in the database
    return redirect('detail', car_id=car_id)


@login_required
def assoc_fluid(request, car_id, fluid_id):
  # Note that you can pass a fluid's id instead of the whole object
    Car.objects.get(id=car_id).fluids.add(fluid_id)
    return redirect('detail', car_id=car_id)



class CarCreate(LoginRequiredMixin, CreateView):
    model = Car
    fields = ['make', 'year', 'model', 'trim', 'mileage']
    def form_valid(self,form):
        # assign logged in user
        form.instance.user = self.request.user #form instance is a car
        return super().form_valid(form)
    

class CarUpdate(LoginRequiredMixin, UpdateView):
    model = Car
    fields = ['mileage', ]


class CarDelete(LoginRequiredMixin, DeleteView):
    model = Car
    success_url = '/cars/'


class FluidCreate(LoginRequiredMixin, CreateView):
    model = Fluid
    fields = ('name', 'weight')


class FluidUpdate(LoginRequiredMixin, UpdateView):
    model = Fluid
    fields = ('name', 'weight')


class FluidDelete(LoginRequiredMixin, DeleteView):
    model = Fluid
    success_url = '/fluids/'


class FluidDetail(LoginRequiredMixin, DetailView):
    model = Fluid
    template_name = 'fluids/detail.html'


class FluidList(LoginRequiredMixin, ListView):
    model = Fluid
    template_name = 'fluids/index.html'

# SIGNUP VIEW FUNCTION
def signup(request):
    error_message = ''
    if request.method == 'POST':
        # how to create a user form object that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # add user to database
            user = form.save()
            # log user in
            login(request, user)
            return redirect('index')
        else: 
            error_message = 'Invalid sign up - try again'
    # a bad POST or GET, render signup.html with empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
    <h1>About the Car Collector</h1>
    <hr />
    <p>Hire the car collector</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>car Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li>
                        <a href="/" class="left brand-logo"> CarCollector</a>
                    </li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'cars_create' %}">Add a Car</a></li>
                    <li><a href="{% url 'index' %}">View My Cars</a></li>
                    <li><a href="{% url 'fluids_create' %}">Add a Fluid</a></li>
                    <li><a href="{% url 'fluids_index' %}">View Fluids</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Log In</a></li>
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
        <div class="right">
            All Rights Reserved, © 2022 Car Collector
        </div>
    </footer>
</body>

</html>

main_app/templates/cars/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Car Details</h1>
<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ car.model }}</span>
                <p>Make: {{ car.make }}</p>
                <p>Model: {{ car.model }} {{ car.trim }}</p>
                <p>Year: {{ car.year }} </p>
                <p>Mileage: {{ car.mileage }} </p>
            </div>
            <div class="card-action">
                <a href="{% url 'car_update' car.id %}">Edit</a>
                <a href="{% url 'car_delete' car.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_maintain' car.id %}" method="post">
            {% csrf_token %} {{ maintain_form.as_p }}
            <input type="submit" class="btn green" value="Add Service" />
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Service</th>
                </tr>
            </thead>
            <tbody>
                {% for maintain in car.maintain_set.all %}
                <tr>
                    <td>{{maintain.date}}</td>
                    <td>{{maintain.get_service_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr />
<div class="row">
    <div class="col s6">
        <h3>{{ car.model }} Fluids</h3>
        {% if car.fluids.count %} {% for fluid in car.fluids.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    <span class="{{ fluid.weight }}">{{ fluid.name }}: {{ fluid.weight }}</span>
                </span>
            </div>
        </div>
        {% endfor %} {% else %}
        <h5>No Fluids :(</h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Fluids</h3>
        {% if fluids.count %}
        {% for fluid in fluids.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    <span class="{{ fluid.weight }}--text">{{ fluid.weight }}</span> {{ fluid.name }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_fluid' car.id fluid.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{cat.name}} Already Has All Fluids Available</h5>
        {% endif %}
    </div>
    <script>
        var dateEl = document.getElementById('id_date');
        M.Datepicker.init(dateEl, {
            format: 'yyyy-mm-dd',
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true
        });
        // additional JS to intialize select
        var selectEl = document.getElementById('id_service');
        M.FormSelect.init(selectEl)
    </script>
    {% endblock %}

main_app/templates/cars/index.html
{% extends 'base.html' %} {% block content %}
<h1>Car List</h1>

{% for car in cars %}
<div class="card">
    <a href="{% url 'detail' car.id %}">
        <div class="card-content">
            <span class="card-title">{{ car.model }}</span>
            <p>Make: {{ car.make }}</p>
            <p>Model: {{ car.model }} {{ car.trim }}</p>
            <p>Year: {{ car.year }} </p>
            <p>Mileage: {{ car.mileage }} </p>
        </div>
    </a>
</div>
{% endfor %}
{% endblock %}

main_app/templates/fluids/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Fluid Details</h1>


<div class="card">
    <a href="{% url 'fluids_detail' fluid.id %}">
        <div class="card-content">
            <span class="card-title"><span class="{{ fluid.name.lower }}-text">{{ fluid.name }}: {{ fluid.weight }}</span></span>
        </div>
        <div class="card-action">
            <a href="{% url 'fluids_update' fluid.id %}">Edit</a>
            <a href="{% url 'fluids_delete' fluid.id %}">Delete</a>
        </div>
    </a>
</div>

{% endblock %}

main_app/templates/fluids/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Fluid List</h1>
{% for fluid in object_list %}
<div class="card">
    <a href="{% url 'fluids_detail' fluid.id %}">
        <div class="card-content">
            <span class="card-title"><span class="{{ fluid.name.lower }}-text">{{ fluid.name }}: {{ fluid.weight }}</span></span>
        </div>
    </a>
</div>
{% endfor %}


{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1> Car Collector Home Page</h1>
{% endblock %}

main_app/templates/main_app/car_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Car</h1>

<h4>
    Are you sure you want to delete
    <span class="teal-text">{{ object.model }} {{object.trim}}</span>?
</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete" class="btn red" />
    <a class="btn" href="{% url 'detail' car.id %}" id="cancel">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/car_form.html
{% extends 'base.html' %} 

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{object.model}} {{object.trim}}</span></h1>
{% else %}
    <h1>Add Car</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="{% if object %} Edit {% else %} Add {% endif %}" class="btn green" />
</form>
{% endblock %}

main_app/templates/main_app/fluid_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Fluid</h1>

<h4>
    Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/fluid_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Update {{ object.name }}</h1>
{% else %}
<h1>Add Fluid</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="{% if object %} Update Fluid {% else %} Add Fluid {% endif %}">
</form>

{% endblock %}